source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.4'
inhibit_all_warnings!

link_with 'pet2share', 'pet2shareTests'

pod 'AMScrollingNavbar', '~> 1.5.1'
pod 'ChameleonFramework', '~> 1.2.1'
pod 'CSStickyHeaderFlowLayout', :head
pod 'EGOCache', :head
pod 'JSONModel', '~> 1.1.0'
pod 'SIAlertView', :head
pod 'pop', :head
pod 'DBCamera', :head
