source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.4'
inhibit_all_warnings!

pod 'AFNetworking', :head
pod 'SIAlertView', :head
pod 'ChameleonFramework', '~> 1.2.0'

post_install do |installer|
 installer.project.targets.each do |target|
  puts "#{target.name}"
 end
end
