source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.4'
inhibit_all_warnings!

pod 'AFNetworking', :head
pod 'AMScrollingNavbar', '~> 1.5.1'
pod 'ChameleonFramework', '~> 1.2.1'
pod 'DBCamera' , '~> 2.4.1'
pod 'JSONModel', '~> 1.1.0'
pod 'Parse', '~> 1.7.5.3'
pod 'ParseUI', '~> 1.1.4'
pod 'SIAlertView', :head
pod 'CSStickyHeaderFlowLayout', :head

post_install do |installer|
 installer.project.targets.each do |target|
  puts "#{target.name}"
 end
end
